FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java","-Xms128m","-Xmx384m","-Xss256k","-XX:+UseContainerSupport",  "-XX:MaxMetaspaceSize=128m", "-XX:+UseSerialGC","-jar","app.jar"]

